# Cars/docker-compose.yml
version: "3.8"

services:
  vue:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vue-dev
    working_dir: /app
    # Bind mount del c√≥digo para desarrollo + volumen para node_modules
    volumes:
      - ./app:/app:delegated
      - node_modules:/app/node_modules
    ports:
      - "5173:5173"
    command: npm run dev -- --host
    stdin_open: true
    tty: true

volumes:
  node_modules:
